name: Run Tests
on: workflow_call
jobs:
  build:
    name: Test Execution
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/vars.env
      
      - name: Run Tests
        working-directory: ./src
        shell: pwsh
        run: |
          dotnet restore "./${{ env.SOLUTION_NAME }}" -s https://www.nuget.org/api/v2/ -s https://nuget.selise.biz/nuget
          dotnet build "./${{ env.SOLUTION_NAME }}" --no-incremental
          dotnet test ./XUnitTests/XUnitTests.csproj /p:CollectCoverage=true --no-build --collect:"XPlat Code Coverage"
          dotnet test "./XUnitTests/XUnitTests.csproj" --no-build --verbosity normal --logger:"junit;LogFilePath=test-results/xunit_results.xml"
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        id: test-results
        if: always()
        with:
          files: "./src/XUnitTests/test-results/*.xml"