name: Web-Build and push at ACR

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      CONTAINER_NAME:
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string
      SERVICE_NAME:
        required: true
        type: string

    secrets:
      SELISE_GITHUB_PAT:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
      MY_GITHUB_PAT:
        required: true
           

env:
  SERVICE_TYPE: "webclient"
  ACR_NAME: selise
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      #Checks out the repository this file is in
      - uses: actions/checkout@v3
        with:
          ref: 'refs/heads/master'
          submodules: "true" 

      - name: Update submodule 
        run: |  
          git submodule update --init
            
      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/vars.env
          
      - name: Set Versions
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/versions.env

      - name: Login to acr
        uses: azure/docker-login@v1
        with: 
          login-server: selise.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push to ACR
        run: |
          docker image build -t ${{ env.ACR_NAME }}.azurecr.io/${{ inputs.CONTAINER_NAME }}:${{ env.IMAGE_TAG }} .
          docker image push ${{ env.ACR_NAME}}.azurecr.io/${{ inputs.CONTAINER_NAME }}:${{ env.IMAGE_TAG }}

      # - name: Set Git commit SHA as environment variable
      #   run: |
      #     echo ${{ env.IMAGE_TAG }}
      #     echo ${{ env.IMAGE_TAG }} >> $GITHUB_ENV 
      #     #echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
      #     # echo "::set-output name=COMMIT_SHA::${{ github.sha }}"
  
  triger-argo:
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Install yq cli tools.
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Checkout the argo repository.
        uses: actions/checkout@v3
        with:
          repository: 'git@github.com:partha-selise/test-argo-target-repo.git'
          token: ${{ secrets.MY_GITHUB_PAT }}
          ref: 'main'

      - name: updating the image tag in respective values file.
        run: |
          cat ./values-file/astonvilla-app.values.yaml
          yq eval '.image.tag = ${{ env.IMAGE_TAG }}' -i ./values-file/astonvilla-app.values.yaml
          cat ./values-file/astonvilla-app.values.yaml
     
     