name: Build (dev)

on:
  push:
    branches:
      - dev
env:
  RUN_UNIT_TEST: "false"
  RUN_SONARQUBE: "false"
  RUN_SNYK: "true"

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
      envvalue2: ${{ steps.setvar.outputs.envvar2 }}
      envvalue3: ${{ steps.setvar.outputs.envvar3 }}
    steps:
      - name: set value
        id: setvar
        run: |
          echo "::set-output name=envvar1::$RUN_UNIT_TEST" 
          echo "::set-output name=envvar2::$RUN_SONARQUBE"
          echo "::set-output name=envvar3::$RUN_SNYK"

  test-job:
    if: ${{ success() && needs.initialization.outputs.envvalue1=='true' }}
    uses: ./.github/workflows/1_test.yml
    needs: [initialization]

  sonarqube-job:
    if: ${{ (success() && needs.initialization.outputs.envvalue1=='true' && needs.initialization.outputs.envvalue2=='true') || (needs.initialization.outputs.envvalue1=='false' && needs.initialization.outputs.envvalue2=='true') }}
    uses: ./.github/workflows/2_sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
    needs: [test-job]
  
  # snyk-job:
  #   if: ${{ success() && needs.initialization.outputs.envvalue3=='true' }}
  #   uses: ./.github/workflows/5_snyk.yml
  #   secrets:
  #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #   needs: [test-job]
  

  cd-job:
    if: (always() && contains(join(needs.*.result, ','), 'failure') == false)
    uses: ./.github/workflows/3_web.yml
    with:
      VERSION: $DEV_VERSION
      CONTAINER_NAME: "dev-$SERVICE_NAME"
      NAMESPACE: "dev-$SERVICE_NAME"
      SERVICE_NAME: $SERVICE_NAME
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.DEV_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}
    needs: [test-job, sonarqube-job]

  cd-job-win:
    if: (always() && contains(join(needs.*.result, ','), 'failure') == false)
    uses: ./.github/workflows/4_win.yml
    with:
      CONTAINER_NAME: "dev-$SERVICE_NAME-win"
      NAMESPACE: "dev-$SERVICE_NAME"
      SERVICE_NAME: $SERVICE_NAME
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.DEV_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}    
    needs: [test-job, sonarqube-job]